name: Build and Push Docker image

on:
    push:
        branches:
            - '**'
        tags:
            - '**'
    pull_request:
        branches:
            - main

permissions:
    contents: read ## let's allow the workflow to read the repository contents
    packages: write ## let's allow the workflow to publish and modify packages (required for ghcr.io)

jobs:
    build-and-push:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Log in to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Extract Docker tag
          id: extract_tag
          run: |
            if [[ "${GITHUB_REF}" == refs/heads/main ]]; then
              echo "tag=latest" >> $GITHUB_OUTPUT
            elif [[ "${GITHUB_REF}" == refs/heads/* ]]; then
              branch=${GITHUB_REF#refs/heads/}
              echo "tag=${branch}" >> $GITHUB_OUTPUT
            elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
              tag=${GITHUB_REF#refs/tags/}
              echo "tag=${tag}" >> $GITHUB_OUTPUT
            else
              echo "tag=dev" >> $GITHUB_OUTPUT
            fi

        - name: Export .env variables to GITHUB_ENV
          run: |
            grep -v '^#' .env | xargs -d '\n' -I {} echo {} >> $GITHUB_ENV

        - name: Build and push Docker image to GHCR and Docker Hub
          uses: docker/build-push-action@v5
          env:
            RE_VERSION: ${{ env.RE_VERSION }}
            BARESIP_VERSION: ${{ env.BARESIP_VERSION }}
            MODULES_LIST: ${{ env.MODULES_LIST }}
          with:
            context: .
            push: true
            tags: |
              ghcr.io/${{ secrets.DOCKERHUB_USERNAME }}/baresip-with-audio:${{ steps.extract_tag.outputs.tag }}
              ${{ secrets.DOCKERHUB_USERNAME }}/baresip-with-audio:${{ steps.extract_tag.outputs.tag }}
            build-args: |
              RE_VERSION=${{ env.RE_VERSION }}
              BARESIP_VERSION=${{ env.BARESIP_VERSION }}
              MODULES_LIST=${{ env.MODULES_LIST }}
